user = 'smallwatt/freenode'
nick = 'smallwatt'
host = 'cerberus.hypermine.com'
port = 6667
channels = ['##vaperefugees']
owner = 'scott@hypermine.com'
password = 'changepass'
admins = [owner]
forecastio_apikey = '4bd781b377742c28ee6bee4ed0f7c5b8'
exclude = ['adminchannel', 'chat', 'lispy', 'rss', 'twss']
helpers = {}
logging = True
excludes = {}
extra = ['/root/jenni/modules/']
external = { '##vaperefugees': ['!'] }
sasl = False
